version: "3.9"
services:
  client:
    build: .
    environment:
      - FLIGHT_COORDINATOR_URI=grpc://coordinator:8888
    command:
      - python3
      - -u
      - client.py
  coordinator:
    build: .
    ports:
      - "8888:8888"
    environment:
      - FLIGHT_DATA_URI=grpc://data:8889
    command:
      - python3
      - -u
      - coordinator.py
  data:
    build: .
    environment:
      - FLIGHT_COORDINATOR_URI=grpc://coordinator:8888
    volumes:
      - /Users/bryce/Data:/data:ro
    command:
      - python3
      - -u
      - data.py
