version: "3.9"
services:
  metadata_server:
    build: .
    command: ./metadata_server 8888
    environment:
      - OPENTELEMETRY_ENABLED=TRUE
      - OPENTELEMETRY_COLLECTOR_URI=http://jaeger:4317
      - DATA_SERVER_HOST=data_server
      - DATA_SERVER_PORT=8889
    ports:
      - "8888:8888"
  data_server:
    build: ./
    command: ./data_server 8889
    environment:
      - OPENTELEMETRY_ENABLED=TRUE
      - OPENTELEMETRY_COLLECTOR_URI=http://jaeger:4317
      - METADATA_SERVER_HOST=metadata_server
      - METADATA_SERVER_PORT=8888
      - FLIGHT_DATASET_DIR=/data
    ports:
      - "8889:8889"
    volumes:
      - ./flight_datasets:/data
  jaeger:
    image: jaegertracing/all-in-one:latest
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    ports:
      - "16686:16686"
      - "4317:4317"
