version: "3.9"
services:
  coordinator:
    build: .
    command: ./coordinator
    environment:
      - OPENTELEMETRY_COLLECTOR_URI=http://jaeger:4317
      - DATA_SERVER_HOST=data
      - DATA_SERVER_PORT=8889
    ports:
      - 8888:5000
  server:
    build: ./
    command: ./server
    environment:
      - OPENTELEMETRY_COLLECTOR_URI=http://jaeger:4317
      - COORDINATOR_URI=grpc://coordinator:5000
      - COORDINATOR_SERVER_HOST=coordinator
      - COORDINATORSERVER_PORT=8888
      - FLIGHT_DATASET_DIR=/data
    ports:
      - 8889:5000
    volumes:
      - ./flight_datasets:/data
  # jaeger:
  #   image: jaegertracing/all-in-one:latest
  #   environment:
  #     - COLLECTOR_OTLP_ENABLED=true
  #   ports:
  #     - "16686:16686"
  #     - "4317:4317"
